name = "LSH"
uuid = "9a8dc858-87cd-50d4-8b18-f2d562f3e4f5"
keywords = ["LSH", "locality", "sensitive", "hashing", "weighted", "minhash"]
license = "MIT"
desc = "Locality Sensitive Hashing in Julia"
version = "0.2.0"

[deps]
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.3,1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[targets]
test = ["Test", "DelimitedFiles"]
